### ISSUE TITLE
[BUG] Install can fail with metadata api server results in non google/aws env

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/gravity#1805]
**Describe the bug**
The metadata api server is called in a cloud environment whether or not the `--cloud-provider=generic` is set.  In the case of a Vultr service provider an error appears to be thrown on the region code. 

A workaround is to block accessing the metadata api with the iptables command.
```bash
iptables -j REJECT -I INPUT 1 -s 169.254.169.254/32
```

**To Reproduce**

Install on Vultr or another service provider that runs a meta data api. 

**Expected behavior**
The metadata api server is not called on a generic env install or it returns an informative message in the install.

**Logs**

```bash
root@wordpress2:~# kubectl get po --all-namespaces
NAMESPACE     NAME                                           READY   STATUS             RESTARTS   AGE
kube-system   coredns-d5crs                                  1/1     Running            0          5m35s
kube-system   dns-app-install-ddfbdd-kt7dc                   0/1     Completed          0          5m45s
kube-system   gravity-install-e1229b-qssd5                   0/1     Completed          0          4m42s
kube-system   gravity-site-w8nfw                             0/1     CrashLoopBackOff   5          4m14s
kube-system   log-collector-588448bfc8-krvrp                 1/1     Running            1          5m13s
kube-system   logging-app-install-92628d-dlcjk               0/1     Completed          0          5m20s
kube-system   lr-aggregator-7df89644fb-h8fsq                 1/1     Running            0          5m13s
kube-system   lr-collector-6nmmk                             1/1     Running            0          5m13s
kube-system   lr-forwarder-6945f599cc-lqkw8                  1/1     Running            0          5m13s
kube-system   monitoring-app-install-eafdab-l4kdt            0/1     Completed          0          5m9s
kube-system   site-app-post-install-ddee7f-l9w2j             0/1     CrashLoopBackOff   5          4m12s
kube-system   storage-app-install-92ef06-zh6dj               0/1     Completed          0          5m31s
kube-system   tiller-app-bootstrap-114c41-kbqcv              0/1     Completed          0          4m48s
kube-system   tiller-deploy-55875f494b-gl55f                 1/1     Running            0          4m44s
monitoring    alertmanager-main-0                            3/3     Running            0          4m47s
monitoring    alertmanager-main-1                            3/3     Running            0          4m34s
monitoring    alertmanager-main-2                            3/3     Running            0          4m24s
monitoring    grafana-679bbb7665-4t5nq                       2/2     Running            0          5m
monitoring    kube-state-metrics-69594c468-7tqdf             3/3     Running            0          4m58s
monitoring    nethealth-c4r4f                                1/1     Running            0          4m52s
monitoring    node-exporter-845p4                            2/2     Running            0          4m57s
monitoring    prometheus-adapter-777999dbb5-zgd5g            1/1     Running            0          4m56s
monitoring    prometheus-k8s-0                               3/3     Running            1          4m40s
monitoring    prometheus-k8s-1                               3/3     Running            1          4m40s
monitoring    prometheus-operator-7bd7d57788-k7fmn           1/1     Running            0          4m58s
monitoring    watcher-7986df4958-vjklw                       1/1     Running            0          4m59s
openebs       maya-apiserver-6486db7bf6-w47ld                1/1     Running            2          5m23s
openebs       openebs-admission-server-c44655c5d-jcjkc       1/1     Running            0          5m23s
openebs       openebs-localpv-provisioner-7c9795f695-lnktt   1/1     Running            0          5m23s
openebs       openebs-ndm-89blf                              1/1     Running            0          5m23s
openebs       openebs-ndm-operator-7c4c784b5f-nqq55          1/1     Running            1          5m23s
openebs       openebs-provisioner-c4cc7fd8b-86p74            1/1     Running            0          5m23s
openebs       openebs-snapshot-operator-7995799c79-29t2l     2/2     Running            0          5m23s
```

```bash
# kubectl logs  gravity-site-w8nfw  -n kube-system
2020-06-26T15:38:02Z INFO [PROCESS]   Starting node labels reconciler. mode:site process/process.go:767
panic: runtime error: slice bounds out of range
goroutine 311 [running]:
github.com/gravitational/gravity/lib/cloudprovider/aws.NewLocalInstance(0x10, 0x10, 0x442cdf)
        /gopath/src/github.com/gravitational/gravity/lib/cloudprovider/aws/aws.go:85 +0x9bd
github.com/gravitational/gravity/lib/process.(*Process).startAutoscale(0xc000432400, 0x4007120, 0xc0008c7740, 0xc0008747a0, 0x0)
        /gopath/src/github.com/gravitational/gravity/lib/process/process.go:524 +0x34
github.com/gravitational/gravity/lib/process.(*Process).initService(0xc000432400, 0x4007120, 0xc0008c7740, 0xc00117ee70, 0xc000712d50)
        /gopath/src/github.com/gravitational/gravity/lib/process/process.go:1497 +0x2958
github.com/gravitational/gravity/lib/process.(*Process).Init(0xc000432400, 0x4007120, 0xc0008c7740, 0x38f2730, 0xe)
        /gopath/src/github.com/gravitational/gravity/lib/process/process.go:328 +0x64
github.com/gravitational/gravity/lib/process.(*Process).Start.func1(0x0, 0x0)
        /gopath/src/github.com/gravitational/gravity/lib/process/process.go:345 +0xe2
github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/service.(*LocalService).Serve(0xc00118bea0, 0xc000000005, 0x3906767)
        /gopath/src/github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/service/supervisor.go:452 +0x2a
github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1(0xc000fbd380, 0x40080e0, 0xc00118bea0)
        /gopath/src/github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/service/supervisor.go:242 +0x33d
created by github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve
        /gopath/src/github.com/gravitational/gravity/vendor/github.com/gravitational/teleport/lib/service/supervisor.go:237 +0x6e
```

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Ubuntu 18.04
 - Gravity [e.g. 5.5.4]: 7.0.11
 - Platform [e.g. Vmware, AWS]: Vultr (that uses VMWare)

**Comment by knisbet** [comment]
Is where the incorrect read on the slice occurs: https://github.com/gravitational/gravity/blob/e9d25e4b302f0c3e8e18f7805f5dce792f740fb1/lib/cloudprovider/aws/aws.go#L85 

Based on preliminary analysis, presumably this occurs because even though installation was with cloud-provider=generic, this particular reconciliation starts and is expected to fail, but is able to contact a metadata server that provides an empty zone, allowing the slice read to panic the process.
